# Generated by Django 4.1.4 on 2022-12-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categorymodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categorys'},
        ),
    ]
