# Generated by Django 4.1.4 on 2022-12-18 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_writemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writemodel',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
